### ISSUE TITLE
Using with shadowed items

### ISSUE THREAD

**Issue by T8RIN** [GIGAMOLE/ComposeFadingEdges#2]
Items with shadow in lazyrow causes weird shadow effect

**Comment by T8RIN** [comment]
![image](https://github.com/GIGAMOLE/ComposeFadingEdges/assets/52178347/8becf546-0cd0-452a-bb20-f5be003403fa)
![image](https://github.com/GIGAMOLE/ComposeFadingEdges/assets/52178347/4cb7b8bd-2264-493c-a57c-8b2d41e8bb09)

**Comment by T8RIN** [comment]
second one is when fading edges is visible

**Comment by GIGAMOLE** [comment]
Hi, can you share a piece of example of how are you using it? Also, try to change the FillType of .fadingEdges, because by default it uses Clip - which clips the child content by applying Xfer mask mode, maybe it causes some issues?

**Comment by T8RIN** [comment]
> Hi, can you share a piece of example of how are you using it? Also, try to change the FillType of .fadingEdges, because by default it uses Clip - which clips the child content by applying Xfer mask mode, maybe it causes some issues?

Maybe it is, i will take a look

**Comment by T8RIN** [comment]
This still persists sadly(
