### ISSUE TITLE
Jitpack not found

### ISSUE THREAD

**Issue by T8RIN** [GIGAMOLE/ComposeFadingEdges#3]
![Screenshot_20240322-070416.png](https://github.com/GIGAMOLE/ComposeFadingEdges/assets/52178347/7fc7dde2-8554-4a80-83ed-8e7cced45d6c)

**Comment by GIGAMOLE** [comment]
Hi. Let me check it.

**Comment by GIGAMOLE** [comment]
The version is there. Also, the newer version is available:
![image](https://github.com/GIGAMOLE/ComposeFadingEdges/assets/7150913/11c04e0b-d6e5-4d08-bf6c-5ccee7e54b36)

**Comment by GIGAMOLE** [comment]
And check your settings.gradle.kts if its correct:

```groovy
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
	    mavenCentral()
	    maven { url 'https://jitpack.io' }
    }
}
```

**Comment by T8RIN** [comment]
It's okay, i've just pushed some commits, and GitHub actions failed with this error again and again, i solved this by forking and releasing repo
